// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dancuulgqpzrnyccxbiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhbmN1dWxncXB6cm55Y2N4Yml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDU0NzAsImV4cCI6MjA2ODMyMTQ3MH0.RmQuDZiQpJKF7gC8WKNJeOyMP_UHDjRA7r3Ie-vlQSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);